### ISSUE TITLE
No ProductKey

### ISSUE THREAD

**Issue by rexobias** [daviiid99/Windows-11-MOD#2]
I'm trying to install the latest Release Preview on a Unsupported Laptop using your ISO (running on Windows 10 with the ISO mounted), but the installer is asking for a ProductKey.

I already tried with some generic and even real ones but nothing works.

**Comment by damolmo** [comment]
That's not the way to install this ISO
Burn it to a USB and boot it

**Comment by rexobias** [comment]
Ok, clean install then. 

Thanks ;)
